version: '3.7'

volumes:
  database_local:

services:
  hjmblog:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: hjmblog
    container_name: hjmblog
    working_dir: /app
    volumes:
      - database_local:/app/database
      - .:/app
    ports:
      - "8000:8000"
    command: /start.sh