version: '3.7'

volumes:
  static:
  database:

services:
  hjmblog:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: hjmblog
    container_name: hjmblog
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: hjmblog_nginx
    container_name: hjmblog_nginx
    volumes:
      - static:/apps/hjmblog/static
    ports:
      - "80:80"
      - "443:443"